apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: tax-calculator-run-
spec:
  pipelineRef:
    name: tax-calculator-pipeline

  workspaces:
    - name: shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi

  params:
    - name: repo-url
      value: https://github.com/ibm-developer-skills-network/zntwk-tax_calculator.git
    - name: repo-revision
      value: main
